/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CarIssue = IDL.Record({
  'model' : IDL.Text,
  'make' : IDL.Text,
  'year' : IDL.Nat,
  'solution' : IDL.Text,
  'issue' : IDL.Text,
});
export const Mechanic = IDL.Record({
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
  'specialization' : IDL.Text,
  'rating' : IDL.Float64,
  'contactDetails' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCarIssue' : IDL.Func([CarIssue], [IDL.Nat], []),
  'addMechanic' : IDL.Func([IDL.Text, Mechanic], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMechanic' : IDL.Func([IDL.Text], [], []),
  'findCarIssues' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Vec(CarIssue)],
      ['query'],
    ),
  'findNearbyMechanics' : IDL.Func(
      [Location, IDL.Float64],
      [IDL.Vec(Mechanic)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCarIssue' : IDL.Func([IDL.Nat], [CarIssue], ['query']),
  'getMechanic' : IDL.Func([IDL.Text], [Mechanic], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMechanic' : IDL.Func([IDL.Text, Mechanic], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CarIssue = IDL.Record({
    'model' : IDL.Text,
    'make' : IDL.Text,
    'year' : IDL.Nat,
    'solution' : IDL.Text,
    'issue' : IDL.Text,
  });
  const Mechanic = IDL.Record({
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
    'specialization' : IDL.Text,
    'rating' : IDL.Float64,
    'contactDetails' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCarIssue' : IDL.Func([CarIssue], [IDL.Nat], []),
    'addMechanic' : IDL.Func([IDL.Text, Mechanic], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMechanic' : IDL.Func([IDL.Text], [], []),
    'findCarIssues' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Vec(CarIssue)],
        ['query'],
      ),
    'findNearbyMechanics' : IDL.Func(
        [Location, IDL.Float64],
        [IDL.Vec(Mechanic)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCarIssue' : IDL.Func([IDL.Nat], [CarIssue], ['query']),
    'getMechanic' : IDL.Func([IDL.Text], [Mechanic], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMechanic' : IDL.Func([IDL.Text, Mechanic], [], []),
  });
};

export const init = ({ IDL }) => { return []; };