/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CarIssue {
  'model' : string,
  'make' : string,
  'year' : bigint,
  'solution' : string,
  'issue' : string,
}
export interface Location { 'latitude' : number, 'longitude' : number }
export interface Mechanic {
  'latitude' : number,
  'name' : string,
  'longitude' : number,
  'specialization' : string,
  'rating' : number,
  'contactDetails' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCarIssue' : ActorMethod<[CarIssue], bigint>,
  'addMechanic' : ActorMethod<[string, Mechanic], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMechanic' : ActorMethod<[string], undefined>,
  'findCarIssues' : ActorMethod<
    [string, string, bigint, string],
    Array<CarIssue>
  >,
  'findNearbyMechanics' : ActorMethod<[Location, number], Array<Mechanic>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCarIssue' : ActorMethod<[bigint], CarIssue>,
  'getMechanic' : ActorMethod<[string], Mechanic>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMechanic' : ActorMethod<[string, Mechanic], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];